# .eas\workflows\publish-preview-update.yml
name: Publish preview update

# on:
#   push:
#     branches: ['*']
on:
  workflow_dispatch: {}
# marking this dormant due to expo free plan limits

jobs:
  publish_preview_update:
    name: Publish preview update
    type: update
    params:
      branch: ${{ github.ref_name || 'test' }}
