const { app, BrowserWindow } = require('electron/main')
const path = require('path')

const isDev = !app.isPackaged

const createWindow = () => {
  const win = new BrowserWindow({
    width: 1200,
    height: 800,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
    },
  })

  if (isDev) {
    // During development, pull directly from the active Next.js hot-reloading local server
    win.loadURL('http://localhost:3000')
    win.webContents.openDevTools()
  } else {
    // In production, serve the compiled static output generated by Next.js
    win.loadFile(path.join(__dirname, '../web/out/index.html'))
  }
}

app.whenReady().then(() => {
  createWindow()

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit()
})
